reinfCalc/accounts/urls.py
from django.urls import path
from accounts import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='singup'),
]

reinfCalc/reinfCalc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('reinfCalcApp.urls')),
]

reinfCalc/reinfCalcApp/urls.py
from django.urls import path
from reinfCalcApp import views


app_name = 'reinfCalcApp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('profile/', views.ProfileInfoView.as_view(), name='profile-info'),
    path('results/', views.ResultsListView.as_view(), name='results'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('sources/', views.SourcesView.as_view(), name='sources'),
    path('results/<int:task_id>', views.ResultsReportView.as_view(), name='results-report'),
    path('run-calculations/', views.run_calculation, name='run-calculation'),
    path('auth-app-user/', views.auth_app_user, name='auth-app-user'),
]

reinfCalc/reinfCalcApp/models.py
from django.db import models

# Create your models here.

reinfCalc/reinfCalcApp/views.py
from django.views.generic import TemplateView, ListView
from django.middleware.csrf import get_token
from django.http import HttpResponse, HttpResponseForbidden, Http404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts import models
from calcEngine import engine
import json


# Create your views here.
class IndexView(TemplateView):
    template_name = 'index.html'


class AboutView(TemplateView):
    template_name = 'about.html'


class ContactView(TemplateView):
    template_name = 'contact.html'


class SourcesView(TemplateView):
    template_name = 'sources.html'


class ProfileInfoView(LoginRequiredMixin, TemplateView):
    context_object_name = 'user'
    template_name = 'reinfCalcApp/user_profile.html'


class ResultsListView(LoginRequiredMixin, ListView):
    """
    Class based view used to display all user's tasks.
    """
    model = models.Task
    template_name = 'reinfCalcApp/results.html'

    def get_queryset(self):
        """
        Return list of Tasks assigned to the currently logged in user

        Overwrite default get_queryset method. Query all Task objects assigned to the current user, sorted by creation
        date. For each task create a dictionary containing its id (for creating a link to the  appropriate report),
        information about the type of the element, and calculation results. Save each dictionary in a list
        which is then returned by the method.
        """
        tasks_query = self.model.objects.filter(owner=self.request.user).order_by('-creation_date')
        tasks = []

        for task_enum in enumerate(tasks_query):
            task_id = task_enum[0]
            task = task_enum[1]

            task_results = json.loads(task.results)

            task_dict = {
                'id': task_id+1,
                'element_type': task.element_type,
                'results': task_results,
            }

            tasks.append(task_dict)

        return tasks


class ResultsReportView(LoginRequiredMixin, ListView):
    """
    Class based view used to display report from the user's task calculations.
    """
    model = models.Task
    context_object_name = 'task'

    def get_template_names(self):
        """
        Get the name of the template based on element type

        Check whether provided id of the task is correct. If yes, access the information about the type of the element
        and return the template's name according to set scheme. Otherwise, render 404 error page.
        """
        if self.task_id > len(self.task_object_query) or self.task_id <= 0:
            raise Http404

        element_type = self.task_object.element_type
        return [f'reports/{element_type}_report.html']

    def get_queryset(self):
        """
        Return the parameters of the task used in the template to render the report page

        Overwrite default get_queryset method. Query all Task objects assigned to the current user, sorted by creation
        date. Access the id of desired task provided by the user in the URL. Check whether the id is correct.
        If yes, parse the results from json string format to a dictionary and return it.
        Otherwise, do not return anything.
        """
        self.task_object_query = self.model.objects.filter(owner=self.request.user).order_by('-creation_date')
        self.task_id = self.kwargs['task_id']

        if self.task_id > len(self.task_object_query) or self.task_id <= 0:
            return None

        self.task_object = self.task_object_query[self.task_id - 1]
        task_parameters = json.loads(self.task_object.results)

        return task_parameters


def auth_app_user(request):
    """
    Function based view used to authenticate the application's users

    Check the information about the request, if the request was not made using python-requests script, render 404 page.
    Otherwise, depending on the request method try to authenticate user (on POST method), or return the CSRF token
    (on GET method).
    """
    user_agent = request.headers['User-Agent']
    if user_agent.startswith('python-requests'):
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return HttpResponse('authenticated')
            else:
                return HttpResponseForbidden('wrong username or password')

        response = HttpResponse(get_token(request))
        return response

    raise Http404


@login_required
def run_calculation(request):
    """
    Function based view used to calculate tasks requested by the application

    Check the information about the request, if the request was not made using python-requests script, render 404 page.
    Otherwise, depending on the request method try to perform calculations (on POST method), or return the CSRF token
    (on GET method). On POST method, read the task parameters from the request, extract information about the type
    of the element, and provide it to the calculation engine's dispatcher. Initialize the element object and run
    calculations. Divide results of the calculations to a response dictionary and results string. Save results to
    the Task model assigned to the appropriate user. Return the response dictionary in the HttpResponse.
    """
    user_agent = request.headers['User-Agent']
    if user_agent.startswith('python-requests'):
        if request.method == 'POST':
            task_parameters = json.loads(request.POST.get('task_parameters'))
            current_user = models.User.objects.get(pk=request.user.id)

            element_type = task_parameters['element'][:-4]
            ElementClass = engine.dispatcher[element_type]
            rc_element = ElementClass(task_parameters)

            calculation_results = rc_element.calc_reinforcement()

            response_dict = json.dumps(calculation_results['results'])
            results_json_string = json.dumps(calculation_results['parameters'])

            task = models.Task(owner=current_user, element_type=element_type, results=results_json_string)
            task.save()

            return HttpResponse(response_dict, content_type='application/json')

        response = HttpResponse(get_token(request))
        return response

    raise Http404

reinfCalc/reinfCalcApp/templates/reinfCalcApp/about.html
{% extends 'reinfCalcApp/base.html' %}

{% block body_block %}
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-2">
        <h1 class="col-md-12 display-5 fw-bold">Reinforcement Calculator Project</h1>
        <p class="col-md-10 fs-4 mt-5">About the project</p>
        <p>Reinforcement Calculator is a desktop application that can be used for dimensioning simple reinforced
            concrete elements. The app is written in Python using PyQt5, requests, json, and math modules.
            It communicates with a Django server, that comes with a calculation engine that produces the task results.
            The server back-end part is written in Python, the front-end part uses Django built-in templating system,
            Bootstrap4, and MathJax.</p>
        <p>All the sources (Desktop App, Django Server, Calculation Engine) are available <a
                class="text-reset" href="{% url 'reinfCalcApp:sources' %}">here</a>.</p>
        <p class="col-md-10 fs-4 mt-5">Using the application</p>
        <p>After installing all required modules listed in requirements.txt file and downloading the current code, the
            application can be started by running main.py script </p>
        <ul>
            <li><p class="col-md-10 fs-5 mt-3">Choosing the element to work with</p></li>
            <p>On start of the application the user is welcomed with the login screen. With the information used to
                create
                the profile user can log in to the application (the server must be online at that time to allow
                authentication of the user).</p>
            <p>Once logged in, a main window of the application shows up letting user choose from 4 types of reinforced
                concrete elements:</p>
            <ul>
                <li>Plate</li>
                <li>Beam</li>
                <li>Column</li>
                <li>Foundation foot</li>
            </ul>
            <p>In order to begin working with a certain element its corresponding button must be clicked.</p>
            <li><p class="col-md-10 fs-5 mt-3">Providing necessary data</p></li>
            <p>Next step is to provide all necessary information about the element, which differ depending on the chosen
                element type. All fields must be filled bearing in mind units stated in the corresponding labels.</p>
            <li><p class="col-md-10 fs-5 mt-3">Using built-in resources</p></li>
            <p>For users' convenience a set of tables containing useful technical parameters has been included in the
                application. It can be accessed either by selecting Resources->Included Data from the menu bar, or using
                <kbd><kbd>ctrl</kbd> + <kbd>i</kbd></kbd>
                keyboard shortcut.</p>
            <li><p class="col-md-10 fs-5 mt-3">Running calculations</p></li>
            <p>All the applications are done server-side, in order to obtain the results for the task user has to ensure
                that following conditions are fulfilled:</p>
            <ul>
                <li>The server is online</li>
                <li>The user has stable internet connection</li>
            </ul>
            <p>If so, in order to obtain the simplified results user has to press a
                <button class="btn btn-secondary btn-sm" disabled>run calculations</button>
                button.
            </p>
            <li><p class="col-md-10 fs-5 mt-3">Generating a report</p></li>
            <p>Users can access the details of a last calculated task via the application pressing a
                <button class="btn btn-secondary btn-sm" disabled>generate report</button>
                button.
            </p>
            <p>Doing so will open the default web browser and load a report page for the last calculated task.</p>
            <p>If the user is not logged in the login page will be displayed first and redirect the user after
                successful authentication.</p>
            <li><p class="col-md-10 fs-5 mt-3">Saving and loading results</p></li>
            <p>At any time of working with the element, users can save their progress using save option by selecting
                File->Save
                from the menu bar, or using <kbd><kbd>ctrl</kbd> + <kbd>s</kbd></kbd> shortcut. The application uses
                JavaScript Object Notation to save the information about the user's progress.</p>
        </ul>
        <p class="col-md-10 fs-4 mt-5">Using the website</p>
        <p>After deploying the Django server using hosting services, or running it locally on the host device users
            gain access to the full functionality of the desktop application. The server comes with an account
            management
            system (users registration and login), a calculation engine, a task results handling system, and an admin
            panel.</p>
        <ul>
            <li><p class="col-md-10 fs-5 mt-3">Site navigation</p></li>
            <p>To navigate on the site user should use links in a navbar and a footer.</p>
            <li><p class="col-md-10 fs-5 mt-3">Creating an account</p></li>
            <p>In order to create an account user should visit the SignUp page using an appropriate link in the
                navbar.</p>
            <p>After successfully creating an account, the user is taken to the login page.</p>
            <li><p class="col-md-10 fs-5 mt-3">Accessing the results</p></li>
            <p>To access the results user first needs to log in.</p>
            <p>Once the user has logged in, the navbar displays additional link - Results. After the user does any
                calculations they'll show up there.</p>
            <p>To access detailed results of calculations, the user has to select task and open the report page using
                the
                <button type="button" class="btn btn-outline-primary btn-sm" disabled>Show Report</button>
                button.
            </p>
        </ul>
    </div>
</div>
{% endblock %}

reinfCalc/reinfCalcApp/templates/reinfCalcApp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reinforcement Calculator</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    {% block head_block %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'reinfCalcApp:index' %}">ReinfCalc</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reinfCalcApp:about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reinfCalcApp:sources' %}">Get Sources</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reinfCalcApp:results'%}">Results</a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reinfCalcApp:profile-info' %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:singup' %}">Sign Up</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container py-4">
    {% block body_block %}
    {% endblock %}
</div>
<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <p class="col-md-4 mb-0 text-muted">Author: Michał Kowal</p>

        <a href="/"
           class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
            <svg class="bi me-2" width="40" height="32">
                <use xlink:href="#bootstrap"></use>
            </svg>
        </a>

        <ul class="nav col-md-4 justify-content-end">
            <li class="nav-item"><a href="{% url 'reinfCalcApp:index' %}" class="nav-link px-2 text-muted">Home</a></li>
            <li class="nav-item"><a href="{% url 'reinfCalcApp:about' %}" class="nav-link px-2 text-muted">About</a></li>
            <li class="nav-item"><a href="{% url 'reinfCalcApp:sources' %}" class="nav-link px-2 text-muted">Get
                Sources</a></li>
            <li class="nav-item"><a href="{% url 'reinfCalcApp:contact' %}" class="nav-link px-2 text-muted">Contact</a></li>
        </ul>
    </footer>
</div>
<script src="{% static 'js/bootstrap.js' %}"></script>
</body>
</html>

reinfCalc/reinfCalcApp/templates/reinfCalcApp/base_report.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Calculations report</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script type="text/javascript" id="MathJax-script" src="{% static 'mathjax/tex-chtml.js' %}" async></script>
    <script type="text/javascript" src="{% static 'mathjax/mathjax_inline.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'reinfCalcApp:index' %}">ReinfCalc</a>
        <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reinfCalcApp:results'%}">Results</a>
                </li>
            </ul>
    </div>
</nav>
<div class="container py-4">
    {% block body_block %}
    {% endblock %}
</div>
<script src="{% static 'js/bootstrap.js' %}"></script>
</body>
</html>

reinfCalc/reinfCalcApp/templates/reinfCalcApp/contact.html
{% extends 'reinfCalcApp/base.html' %}
{% load static %}

{% block body_block %}
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-2">
        <h1 class="col-md-12 display-5 fw-bold">Contact the app author:</h1>
        <div class="card mt-5" style="max-width: 1080px;">
            <div class="row g-0">
                <div class="col-md-4 m-auto">
                    <img src="{% static 'img/contact_placeholder.png'%}" class="img-fluid rounded-start" alt="placeholder contact picture">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">Michał Kowal</h5>
                        <p class="card-text">Civil Engineering student at Cracow University of Technology, programming
                            enthusiast.</p>
                        <p class="card-text">Feel free to contact me via my e-mail:</p>
                        <p class="card-text fs-5">michal.kowal.66@gmail.com</p>
                        <p class="card-text">Or reach out to me using one of my media links:</p>
                        <div class="fs-5 mb-3">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-linkedin" viewBox="0 0 16 16">
                                <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"></path>
                            </svg>
                            <a class="text-reset" href="https://www.linkedin.com/in/micha%C5%82-kowal-03b945234/">LinkedIn</a>
                        </div>
                        <div class="fs-5 mb-3">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-github" viewBox="0 0 16 16">
                                <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
                            </svg>
                            <a class="text-reset" href="https://github.com/michalkowal66">GitHub</a>
                        </div>
                        <p class="card-text"><small class="text-muted"></small></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

reinfCalc/reinfCalcApp/templates/reinfCalcApp/index.html
{% extends 'reinfCalcApp/base.html' %}
{% load static %}

{% block body_block %}
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-2">
        <h1 class="col-md-12 display-5 fw-bold">Welcome to ReinfCalc!</h1>
        <p class="col-md-12 fs-4 mt-5">Reinforcement Calculator is a desktop application that can be used for dimensioning
            simple reinforced concrete elements.</p>
        <p class="col-md-10 fs-4">To start visit the <a class="text-reset" href="{% url 'reinfCalcApp:about' %}">About</a> page.</p>
         <div class="row row-cols-1 row-cols-md-2 g-4 mt-4">
            <div class="col">
                <div class="card">
                    <img src="{% static 'img/signup.jpg' %}" class="card-img-top border border-dark" alt="signup page">
                    <div class="card-body">
                        <h5 class="card-title">1. Create an account</h5>
                        <p class="card-text">You can create an account using the options in the navbar.</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <img src="{% static 'img/sources.jpg' %}" class="card-img-top border border-dark" alt="get sources page">
                    <div class="card-body">
                        <h5 class="card-title">2. Get sources</h5>
                        <p class="card-text">Download the latest version of the application, and install the requirements according to the instructions.</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <img src="{% static 'img/main_screen.jpg' %}" class="card-img-top border border-dark" alt="application main screen">
                    <div class="card-body">
                        <h5 class="card-title">3. Choose an element to work with</h5>
                        <p class="card-text">Log in to the application with your account. Choose one of the available types of elements.</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <img src="{% static 'img/results.jpg' %}" class="card-img-top border border-dark" alt="example of a task report">
                    <div class="card-body">
                        <h5 class="card-title">4. Calculate it and check results</h5>
                        <p class="card-text">After providing all the necessary data run the calculations. You'll be able to access the results both in the application (simplified) and the website (detailed report)!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

reinfCalc/reinfCalcApp/templates/reinfCalcApp/results.html
{% extends 'reinfCalcApp/base.html' %}
{% load static %}
{% load custom_filters %}

{% block head_block %}
    <script type="text/javascript" id="MathJax-script" src="{% static 'mathjax/tex-chtml.js' %}" async></script>
    <script type="text/javascript" src="{% static 'mathjax/mathjax_inline.js' %}"></script>
{% endblock %}

{% block body_block %}
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-2">
        {% if object_list %}
        <h1 class="col-md-12 display-5 fw-bold">Here are your most recent results:</h1>
        <div class="accordion mt-5" id="accordionExample">
            {% for task in object_list %}
            <div class="accordion" id="resultsAccordion">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="heading{{task.id}}">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapse{{task.id}}" aria-expanded="true"
                                aria-controls="collapse{{task.id}}">
                            {{task.results.self}}
                        </button>
                    </h2>
                    <div id="collapse{{task.id}}" class="accordion-collapse collapse"
                         aria-labelledby="heading{{task.id}}">
                        <div class="accordion-body">
                            <p class="col-md-10 fs-5">Task results:</p>
                                {% if task.element_type == "column" %}
                                    {% if task.results.provided_area_1 %}
                                        <p>Provided reinforcement area in the $1^{st}$ group: ${{ task.results.provided_area_1 | m2TOcm2 }} cm^2$</p>
                                        <p>Provided bars in the $1^{st}$ group: {{ task.results.provided_bars_1 }}</p>
                                    {% else %}
                                        <p>Wasn't able to calculate reinforcement for the $1^{st}$ group.</p>
                                    {% endif %}
                                    {% if task.results.provided_area_2 %}
                                        <p>Provided reinforcement area in the $2^{nd}$ group: ${{ task.results.provided_area_2 | m2TOcm2 }} cm^2$</p>
                                        <p>Provided bars in the $2^{nd}$ group: {{ task.results.provided_bars_2 }}</p>
                                    {% else %}
                                        <p>Wasn't able to calculate reinforcement for the $2^{nd}$ group.</p>
                                    {% endif %}
                                    {% if task.results.required_area_1 %}
                                        <p>Required reinforcement area for the $1^{st}$ group: ${{task.results.required_area_1 | m2TOcm2 }} cm^2$</p>
                                    {% else %}
                                        <p>Wasn't able to calculate required area for the $1^{st}$ group.</p>
                                    {% endif %}
                                    {% if task.results.required_area_2 %}
                                        <p>Required reinforcement area for the $2^{nd}$ group: ${{task.results.required_area_2 | m2TOcm2 }} cm^2$</p>
                                    {% else %}
                                        <p>Wasn't able to calculate required area for the the $2^{nd}$ group.</p>
                                    {% endif %}
                                {% else %}
                                    {% if task.results.provided_area %}
                                        <p>Provided reinforcement area: ${{ task.results.provided_area | m2TOcm2 }} cm^2$</p>
                                        {% if task.element_type == "plate" or task.element_type == "foot" %}
                                            <p>Provided reinforcement spacing: ${{ task.results.provided_spacing | mTOcm }} cm$</p>
                                        {% elif task.element_type == "beam" %}
                                            <p>Provided bars: {{ task.results.provided_bars }}</p>
                                        {% endif %}
                                    {% else %}
                                        <p>Wasn't able to calculate reinforcement for the task.</p>
                                    {% endif %}
                                    {% if task.results.required_area %}
                                        <p>Required reinforcement area: ${{task.results.required_area | m2TOcm2 }} cm^2$</p>
                                    {% else %}
                                        <p>Wasn't able to calculate required area for the task.</p>
                                    {% endif %}
                                {% endif %}
                                <a class="btn btn-outline-primary" href="{% url 'reinfCalcApp:results-report' task_id=task.id %}">Show report</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        {% else %}
        <h1 class="col-md-12 display-5 fw-bold">No results found...</h1>
        <p class="col-md-12 fs-4 mb-2 mt-5">Seems like you haven't done any calculations yet!</p>
        <p class="col-md-10 fs-4 mb-2">Login to your account in the reinfCalc application and run calculations to see them
            here.</p>
        {% endif %}

    </div>
</div>
</div>
{% endblock%}

reinfCalc/reinfCalcApp/templates/reinfCalcApp/sources.html
{% extends 'reinfCalcApp/base.html' %}

{% block body_block %}
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-2">
        <h1 class="col-md-12 display-5 fw-bold">Get the latest sources:</h1>
        <p class="col-md-12 fs-4 mb-5 mt-5">Here you can download all necessary files needed to obtain full functionality of the project.</p>
        <ul>
            <ol><p class="col-md-10 fs-4 mb-2">ReinfCalc desktop application <a class="text-reset" href="https://github.com/michalkowal66/reinfCalc">source</a>.</p></ol>
            <ol><p class="col-md-10 fs-4 mb-2">Calculation engine of the application <a class="text-reset" href="https://github.com/michalkowal66/reinfCalcEngine">source</a>.</p></ol>
            <ol><p class="col-md-10 fs-4">Django server <a class="text-reset" href="https://github.com/michalkowal66/reinfCalcServer">source</a>.</p></ol>
        </ul>
        <p class="col-md-12 fs-4 mt-5 mb-2">You can also visit the <a class="text-reset" href="{% url 'reinfCalcApp:about' %}">About</a> page if you need some more information or instructions.</p>
        <p class="col-md-12 fs-4">Or contact the app authors <a class="text-reset" href="{% url 'reinfCalcApp:contact' %}">here</a>.</p>
    </div>
</div>
{% endblock %}